node {

    checkout scm

    env.DOCKER_API_VERSION="1.23"

    sh "git rev-parse --short HEAD > commit-id"

    tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "hello-airwolfnh"
    registryHost = "docker.io/airwolfnh/"
    imageName = "${registryHost}${appName}:${tag}"
    env.BUILDIMG=imageName
    stage "Build"
        sh "docker build -t ${imageName} -f application/k8s/Dockerfile application/hello-airwolfnh"

    stage "Push"
        withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'password', usernameVariable: 'username')]) {
        sh "docker login -u ${username} -p ${password}"}
        sh "docker push ${imageName}"

    stage "Deploy"
        sh "sed 's#__IMAGE__#'$BUILDIMG'#' application/k8s/deployment.yaml | kubectl apply -f -"
}
